sudo: False

language: python

matrix:
  include:
    - python: 2.7
    - python: 3.6

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-streamz python=$TRAVIS_PYTHON_VERSION pytest tornado toolz flake8 coverage codecov networkx graphviz python-graphviz dask distributed pandas bokeh ipython ipykernel ipywidgets -c conda-forge -c bokeh
  - source activate test-streamz
  - pip install git+https://github.com/dask/distributed.git --upgrade --no-deps

  - python setup.py install

script:
  - coverage run run_tests.py --runslow
  - flake8 streamz

after_success:
  - codecov

notifications:
  email: false
